### ISSUE TITLE
Dtr 2020

### ISSUE THREAD

**Issue by andrasq420** [Teaching-projects/SOE-DTR-2020-Stress-Kurucz#1]
Szia! 
 Feltöltöttem a fájlokat a mostani állapotukban. Légyszives ránézel ? :D

**Comment by hegyhati** [comment]
Ahoj. Tetszik, 4/5-on allok most.

Azt nem teljesen ertem, miert osztasz 6-tal a stressz szamitasnal.

Miert nem lehet tovabba egy nap tobb beadandot csinalni? Azt modntad, kemeny vagy :-D 

Lehetne ilyenen gondolkodni, hogyha 70 a stressz limitem, de a beadando 100-ra feltolja, majd a jatek leviszi 50-el, akkor a jatek elott "megdoglok-e". De ezt el tudom engedni, mert mondjuk "valtogatva" csinalom.  Persze ha meg lehet szakitani ezeket, akkor felvetodik olyan kerdes is, hogy szetdobhatom-e tobb napra, stb. De mondom, ezt engedjuk el, messzire vezet.

Viszont a celfuggveny igy nem tul erdekes, mert ugyanazt piszkalja, amire a korlatozas van. A korlatozasok effektive beallitanak mar egy hatart a celfuggvenyre. Szoval minden beadando mellett annyit viszunk le a stresszen, amennyit lehet. Annak sincs tul sok jelentosege, hogy a napokon hogy permutalom a feladatokat, mert minden nap ugyanolyan hosszu. Ezek miatt igazabol "trivialis" a megoldas. EGyik nap ott lesz a DTR, az ennyi ido, meg ennyire viszi fel, aztan probalom 0-nak minnel inkabb a kozelebe levinni.

Hogy tenyleg "izgalmas" feladat legyen, 2 dolgot javasolnek: 
1) a napok ne legyenek ugyanolyan hosszuak (Egyeb elfeoglaltsagok miatt), ez az alapstresszi s napfuggo legyen (egyeb elfoglaltsagok miatt)
2) Minden jatekhzoz legyen egy olyan, hogy "mennyire gyilkolja a szemet", es a celfuggveny mondjuk ennek a minimalizalasa lenne. 

Ezeket nem sok beletenni, elnezve, hogy a tobbit milyen szepen megcsinaltad, szerintem hamar menni fog, es akkor siman adom az otost. MErt amugy tenyleg szepen kivitelezett munka, tetszik.

**Comment by andrasq420** [comment]
Nem tudom hogy így gondoltad-e de megpróbáltam megcsinálni.
Nem tudom a szemromlásnak van-e tényleges mértékegysége úgyhogy most az csak egymáshoz hasonlítható.

**Comment by hegyhati** [comment]
Jo lesz, irom az otost.
